import { useState } from "react";
import { useGetReleases, getGetReleasesQueryKey, type Release } from "@workspace/api-client-react";
import { ChevronDown, ChevronUp, Tag, ExternalLink } from "lucide-react";

const OWNER = "humbertobellor";
const REPO  = "dossier";

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

const AUTO_GENERATED_RE = /^automated release from replit push/i;

function isAutoGenerated(body: string | null): boolean {
  if (!body) return false;
  return AUTO_GENERATED_RE.test(body.trim());
}

const INK   = "#14110B";
const TEAL  = "#1B4E4A";
const V50   = "#FAF6EC";
const V100  = "#F3ECD9";
const V200  = "#E7DCC0";
const V300  = "#CFBE96";
const V400  = "#9C8A64";
const V500  = "#6B5C3E";

type InlineNode =
  | { type: "text"; value: string }
  | { type: "bold"; children: InlineNode[] }
  | { type: "italic"; children: InlineNode[] }
  | { type: "code"; value: string }
  | { type: "link"; href: string; children: InlineNode[] };

function parseInline(text: string): InlineNode[] {
  const nodes: InlineNode[] = [];
  let i = 0;
  let buf = "";

  const flush = () => {
    if (buf) { nodes.push({ type: "text", value: buf }); buf = ""; }
  };

  while (i < text.length) {
    if (text[i] === "`") {
      const end = text.indexOf("`", i + 1);
      if (end !== -1) {
        flush();
        nodes.push({ type: "code", value: text.slice(i + 1, end) });
        i = end + 1;
        continue;
      }
    }

    if (text[i] === "[") {
      const closeBracket = text.indexOf("]", i + 1);
      if (closeBracket !== -1 && text[closeBracket + 1] === "(") {
        const closeParen = text.indexOf(")", closeBracket + 2);
        if (closeParen !== -1) {
          flush();
          const linkText = text.slice(i + 1, closeBracket);
          const href = text.slice(closeBracket + 2, closeParen);
          nodes.push({ type: "link", href, children: parseInline(linkText) });
          i = closeParen + 1;
          continue;
        }
      }
    }

    if (text[i] === "*" && text[i + 1] === "*") {
      const end = text.indexOf("**", i + 2);
      if (end !== -1) {
        flush();
        nodes.push({ type: "bold", children: parseInline(text.slice(i + 2, end)) });
        i = end + 2;
        continue;
      }
    }

    if (text[i] === "*" && text[i + 1] !== "*") {
      const end = text.indexOf("*", i + 1);
      if (end !== -1) {
        flush();
        nodes.push({ type: "italic", children: parseInline(text.slice(i + 1, end)) });
        i = end + 1;
        continue;
      }
    }

    buf += text[i];
    i++;
  }
  flush();
  return nodes;
}

function renderInline(nodes: InlineNode[], keyPrefix: string): React.ReactNode[] {
  return nodes.map((node, idx) => {
    const key = `${keyPrefix}-${idx}`;
    switch (node.type) {
      case "text":
        return <span key={key}>{node.value}</span>;
      case "bold":
        return <strong key={key} style={{ fontWeight: 700, color: V500 }}>{renderInline(node.children, key)}</strong>;
      case "italic":
        return <em key={key} style={{ fontStyle: "italic" }}>{renderInline(node.children, key)}</em>;
      case "code":
        return (
          <code
            key={key}
            style={{
              fontFamily: "monospace",
              fontSize: "0.85em",
              background: V200,
              color: TEAL,
              padding: "1px 5px",
              borderRadius: "3px",
            }}
          >
            {node.value}
          </code>
        );
      case "link": {
        const safeHref = /^https?:\/\//i.test(node.href) ? node.href : null;
        return safeHref ? (
          <a
            key={key}
            href={safeHref}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: TEAL, textDecoration: "underline", textUnderlineOffset: "2px" }}
          >
            {renderInline(node.children, key)}
          </a>
        ) : (
          <span key={key}>{renderInline(node.children, key)}</span>
        );
      }
    }
  });
}

type BlockNode =
  | { type: "heading"; level: 1 | 2 | 3; inline: InlineNode[] }
  | { type: "paragraph"; inline: InlineNode[] }
  | { type: "bullet_list"; items: InlineNode[][] }
  | { type: "code_block"; lang: string; code: string };

function parseBlocks(markdown: string): BlockNode[] {
  const lines = markdown.split("\n");
  const blocks: BlockNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.startsWith("```")) {
      const lang = line.slice(3).trim();
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++;
      blocks.push({ type: "code_block", lang, code: codeLines.join("\n") });
      continue;
    }

    const headingMatch = /^(#{1,3})\s+(.+)$/.exec(line);
    if (headingMatch) {
      const level = headingMatch[1].length as 1 | 2 | 3;
      blocks.push({ type: "heading", level, inline: parseInline(headingMatch[2]) });
      i++;
      continue;
    }

    if (/^[-*]\s/.test(line)) {
      const items: InlineNode[][] = [];
      while (i < lines.length && /^[-*]\s/.test(lines[i])) {
        items.push(parseInline(lines[i].replace(/^[-*]\s+/, "")));
        i++;
      }
      blocks.push({ type: "bullet_list", items });
      continue;
    }

    if (line.trim() === "") {
      i++;
      continue;
    }

    const paraLines: string[] = [];
    while (i < lines.length && lines[i].trim() !== "" && !/^(#{1,3}\s|```|[-*]\s)/.test(lines[i])) {
      paraLines.push(lines[i]);
      i++;
    }
    if (paraLines.length > 0) {
      blocks.push({ type: "paragraph", inline: parseInline(paraLines.join(" ")) });
    }
  }

  return blocks;
}

function MarkdownBody({ markdown }: { markdown: string }) {
  const blocks = parseBlocks(markdown);

  return (
    <div
      style={{
        marginTop: "0.5rem",
        fontFamily: "var(--font-body)",
        fontSize: "var(--fs-xs)",
        color: V500,
        lineHeight: 1.6,
        display: "flex",
        flexDirection: "column",
        gap: "0.4rem",
      }}
      data-testid="changelog-release-body"
    >
      {blocks.map((block, bi) => {
        const key = `block-${bi}`;
        switch (block.type) {
          case "heading": {
            const sizeMap: Record<1 | 2 | 3, string> = {
              1: "0.9em",
              2: "0.85em",
              3: "0.8em",
            };
            return (
              <p
                key={key}
                style={{
                  fontWeight: 700,
                  fontSize: sizeMap[block.level],
                  color: TEAL,
                  margin: 0,
                  marginTop: bi > 0 ? "0.25rem" : 0,
                }}
              >
                {renderInline(block.inline, key)}
              </p>
            );
          }
          case "paragraph":
            return (
              <p key={key} style={{ margin: 0 }}>
                {renderInline(block.inline, key)}
              </p>
            );
          case "bullet_list":
            return (
              <ul
                key={key}
                style={{
                  margin: 0,
                  paddingLeft: "1.1em",
                  display: "flex",
                  flexDirection: "column",
                  gap: "0.15rem",
                  listStyleType: "disc",
                }}
              >
                {block.items.map((item, ii) => (
                  <li key={`${key}-${ii}`} style={{ paddingLeft: "0.2em" }}>
                    {renderInline(item, `${key}-${ii}`)}
                  </li>
                ))}
              </ul>
            );
          case "code_block":
            return (
              <pre
                key={key}
                style={{
                  margin: 0,
                  padding: "0.5rem 0.625rem",
                  background: V100,
                  border: `1px solid ${V200}`,
                  borderRadius: "4px",
                  fontFamily: "monospace",
                  fontSize: "0.8em",
                  color: INK,
                  overflowX: "auto",
                  whiteSpace: "pre",
                }}
              >
                <code>{block.code}</code>
              </pre>
            );
        }
      })}
    </div>
  );
}

export function Changelog() {
  const [open, setOpen] = useState(false);

  const { data: releases, status } = useGetReleases({
    query: {
      queryKey: getGetReleasesQueryKey(),
      enabled:   open,
      staleTime: 1000 * 60 * 5,
      gcTime:    1000 * 60 * 30,
      retry: 1,
    },
  });

  const latest = releases?.[0];

  return (
    <div
      style={{
        borderTop: `1px solid ${V200}`,
        paddingTop: "1.25rem",
        marginTop: "1.25rem",
        width: "100%",
      }}
      data-testid="changelog"
    >
      <button
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        style={{
          display: "flex",
          alignItems: "center",
          gap: "6px",
          background: "none",
          border: "none",
          cursor: "pointer",
          padding: 0,
          fontFamily: "var(--font-ui)",
          fontSize: "var(--fs-xs)",
          fontWeight: 600,
          letterSpacing: "0.05em",
          textTransform: "uppercase",
          color: open ? TEAL : V500,
          transition: "color 0.15s",
        }}
        data-testid="changelog-toggle"
      >
        <Tag size={11} />
        Site Updates
        {status === "pending" ? (
          <span style={{ color: V400, fontWeight: 400 }}>…</span>
        ) : latest ? (
          <span
            style={{
              fontFamily: "var(--font-ui)",
              fontSize: "10px",
              fontWeight: 600,
              letterSpacing: "0.04em",
              padding: "2px 7px",
              borderRadius: "var(--radius-sm)",
              background: open ? "rgba(27,78,74,0.08)" : V100,
              color: open ? TEAL : V400,
              border: `1px solid ${open ? "rgba(27,78,74,0.2)" : V200}`,
              transition: "all 0.15s",
            }}
            data-testid="changelog-latest-tag"
          >
            {latest.tag_name}
          </span>
        ) : null}
        {open ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
      </button>

      {open && (
        <div
          style={{ marginTop: "1rem", display: "flex", flexDirection: "column", gap: "0.75rem" }}
          data-testid="changelog-list"
        >
          {status === "pending" && (
            <p style={{ fontFamily: "var(--font-ui)", fontSize: "var(--fs-xs)", color: V400 }}>
              Loading releases…
            </p>
          )}
          {status === "error" && (
            <p style={{ fontFamily: "var(--font-ui)", fontSize: "var(--fs-xs)", color: V400 }}>
              Could not load releases.
            </p>
          )}
          {status === "success" && releases.length === 0 && (
            <p style={{ fontFamily: "var(--font-ui)", fontSize: "var(--fs-xs)", color: V400 }}>
              No releases yet.
            </p>
          )}
          {status === "success" &&
            releases.map((release) => (
              <ReleaseRow key={release.id} release={release} />
            ))}
          <a
            href={`https://github.com/${OWNER}/${REPO}/releases`}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "4px",
              fontFamily: "var(--font-ui)",
              fontSize: "var(--fs-xs)",
              fontWeight: 500,
              color: TEAL,
              textDecoration: "none",
              marginTop: "0.25rem",
              opacity: 0.8,
            }}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = "1"; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = "0.8"; }}
            data-testid="changelog-all-releases"
          >
            View all releases on GitHub <ExternalLink size={10} />
          </a>
        </div>
      )}
    </div>
  );
}

function ReleaseRow({ release }: { release: Release }) {
  const [bodyOpen, setBodyOpen] = useState(false);

  const body = release.body?.trim() ?? null;
  const hasHumanNotes = !!body && !isAutoGenerated(body);

  return (
    <div
      style={{
        background: V50,
        border: `1px solid ${V200}`,
        borderRadius: "var(--radius-md)",
        padding: "0.625rem 0.875rem",
        borderLeft: `3px solid ${TEAL}`,
      }}
      data-testid="changelog-release"
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "0.5rem", flexWrap: "wrap" }}>
        <a
          href={release.html_url}
          target="_blank"
          rel="noopener noreferrer"
          style={{
            fontFamily: "var(--font-ui)",
            fontSize: "var(--fs-xs)",
            fontWeight: 700,
            letterSpacing: "0.04em",
            color: TEAL,
            textDecoration: "none",
          }}
          onMouseEnter={(e) => { e.currentTarget.style.textDecoration = "underline"; }}
          onMouseLeave={(e) => { e.currentTarget.style.textDecoration = "none"; }}
          data-testid="changelog-release-tag"
        >
          {release.tag_name}
        </a>
        <span
          style={{
            fontFamily: "var(--font-ui)",
            fontSize: "10px",
            fontWeight: 500,
            color: V400,
            letterSpacing: "0.03em",
            flexShrink: 0,
          }}
          data-testid="changelog-release-date"
        >
          {formatDate(release.published_at)}
        </span>
      </div>

      {hasHumanNotes && (
        <>
          {!bodyOpen ? (
            <button
              onClick={() => setBodyOpen(true)}
              style={{
                display: "block",
                marginTop: "0.25rem",
                background: "none",
                border: "none",
                padding: 0,
                cursor: "pointer",
                fontFamily: "var(--font-ui)",
                fontSize: "10px",
                fontWeight: 500,
                color: V400,
                letterSpacing: "0.03em",
              }}
            >
              Show notes
            </button>
          ) : (
            <>
              <MarkdownBody markdown={body!} />
              <button
                onClick={() => setBodyOpen(false)}
                style={{
                  display: "block",
                  marginTop: "0.375rem",
                  background: "none",
                  border: "none",
                  padding: 0,
                  cursor: "pointer",
                  fontFamily: "var(--font-ui)",
                  fontSize: "10px",
                  fontWeight: 500,
                  color: V400,
                  letterSpacing: "0.03em",
                }}
              >
                Hide notes
              </button>
            </>
          )}
        </>
      )}
    </div>
  );
}
